### ISSUE TITLE
0.0.11 is not compatible with 1.20.1

### ISSUE THREAD

**Issue by LeinyerTRS** [ItemsAdder/ItemsAdderBlocksInjector#14]
you are missing the nms_v1_20_r1 folder in version 0.0.11, that's why it doesn't work in 1.20.1.

**Comment by LoneDev6** [comment]
The file exists.
Download [here](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/releases/tag/0.0.11).

![Image](https://github.com/ItemsAdder/ItemsAdderBlocksInjector/assets/27242001/dd7b0021-4aec-4b99-839a-a09cc5080240)

**Comment by LoneDev6** [comment]
please post an actual server log so i can check why it failed to load.

**Comment by LeinyerTRS** [comment]
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode, sharing)
container@pterodactyl~ java -XX:+UseContainerSupport -Xms128M -Xmx8192M -Dlog4j2.formatMsgNoLookups=true -jar server.jar
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8+7) Host: Linux 3.10.0-1127.19.1.el7.x86_64 (amd64)
Loading libraries, please wait...
[00:58:13 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:58:14 INFO]: Loaded 7 recipes
[00:58:15 INFO]: Starting minecraft server version 1.20.1
[00:58:15 INFO]: Loading properties
[00:58:15 INFO]: This server is running Purpur version git-Purpur-2023 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 41b121b on HEAD)
[00:58:15 INFO]: Server Ping Player Sample Count: 12
[00:58:15 INFO]: Using 4 threads for Netty based IO
[00:58:15 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[00:58:16 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[00:58:16 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[00:58:16 WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[00:58:16 WARN]: [Pufferfish] Debug: Java: 17.0.8, test run: true
[00:58:16 INFO]: Default game type: SURVIVAL
[00:58:16 INFO]: Generating keypair
[00:58:16 INFO]: Starting Minecraft server on 0.0.0.0:25583
[00:58:16 INFO]: Using epoll channel type
[00:58:16 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[00:58:16 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[00:58:16 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/itemsadder-blocks-injector_0.0.11.jar' in 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ViaVersion]. Please download and install these plugins to run 'ItemsAdderBlocksInjector'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2023]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:58:17 INFO]: [WolfyUtilities] NMS Version: v1_20_R1
[00:58:17 INFO]: [me.wolfyscript.lib.org.reflections.Reflections] Reflections took 363 ms to scan 1 urls, producing 1266 keys and 4001 values
[00:58:18 INFO]: [AngelChest] Hooked into WorldGuard 7.0.9-beta1+2249-223b80c
[00:58:18 INFO]: [CustomCrafting] NMS Version: v1_20_R1
[00:58:19 INFO]: [WorldEdit] Loading server plugin WorldEdit v7.2.15+6463-5ca4dff
[00:58:19 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@68958526]
[00:58:19 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0-SNAPSHOT-661
[00:58:21 INFO]: [WorldGuard] Loading server plugin WorldGuard v7.0.9-beta1+2249-223b80c
[00:58:21 INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.3
[00:58:21 INFO]: [LibsDisguises] Loading server plugin LibsDisguises v10.0.37
[00:58:21 INFO]: [BKCommonLib] Loading server plugin BKCommonLib v1.20.1-v1
[00:58:24 WARN]: [org.bukkit.craftbukkit.v1_20_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[00:58:29 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.98
[00:58:29 INFO]: [MythicMobs] Loading server plugin MythicMobs v5.3.5-64893d49
[00:58:29 INFO]: [LumineUtils] (io.lumine.mythic.bukkit.utils.) is bound to plugin MythicMobs - io.lumine.mythic.bukkit.MythicBukkit
[00:58:29 INFO]: [My_Worlds] Loading server plugin My_Worlds v1.20.1-v1
[00:58:29 INFO]: [SkinsRestorer] Loading server plugin SkinsRestorer v14.2.12
[00:58:29 INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.25
[00:58:29 INFO]: [Essentials] Loading server plugin Essentials v2.20.1-dev+37-b2ae28b
[00:58:29 INFO]: [ModelEngine] Loading server plugin ModelEngine vR3.1.8
[00:58:29 INFO]: [FileGUI] Loading server plugin FileGUI vPhase 67
[00:58:29 INFO]: [AntiAltAccount] Loading server plugin AntiAltAccount vPhase 32
[00:58:29 INFO]: [UltimateStatistics] Loading server plugin UltimateStatistics vPhase 134
[00:58:29 INFO]: [dynmap] Loading server plugin dynmap v3.6-899
[00:58:29 INFO]: [dynmap] version=git-Purpur-2023 (MC: 1.20.1)
[00:58:29 INFO]: [dynmap] Mod Support API available
[00:58:29 INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.5.0c-r3
[00:58:29 INFO]: [WolfyUtilities] Loading server plugin WolfyUtilities v4.16.12.1
[00:58:29 INFO]: [WolfyUtilities] Generate Functional Recipes
[00:58:29 INFO]: [WolfyUtilities] Register JSON de-/serializers
[00:58:29 INFO]: [WolfyUtilities] Register JSON Operators
[00:58:29 INFO]: [WolfyUtilities] Register JSON Value Providers
[00:58:29 INFO]: [WolfyUtilities] Register CustomItem NBT Checks
[00:58:29 INFO]: [WolfyUtilities] Register CustomItem Actions
[00:58:29 INFO]: [WolfyUtilities] Register CustomItem Events
[00:58:29 INFO]: [WolfyUtilities] Register Particle Animators
[00:58:29 INFO]: [WolfyUtilities] Register Particle Shapes
[00:58:29 INFO]: [WolfyUtilities] Register Particle Timers
[00:58:29 INFO]: [WolfyUtilities] Register Custom Block Data
[00:58:29 INFO]: [WolfyUtilities] Register Custom Player Data
[00:58:29 INFO]: [WolfyUtilities] Register NBT Query Nodes
[00:58:29 INFO]: [spark] Loading server plugin spark v1.10.43
[00:58:29 INFO]: [nAntiBot] Loading server plugin nAntiBot v6.0.13
[00:58:30 INFO]: [Spartan] Loading server plugin Spartan vPhase 516.1
[00:58:30 INFO]: [TAB] Loading server plugin TAB v4.0.3
[00:58:30 INFO]: [DiscordSRV] Loading server plugin DiscordSRV v1.26.2

**Comment by LeinyerTRS** [comment]
I already solved it by reading the console, I was missing a plugin as a dependency that I didn't know I was using, it was ViaVersion.
