### ISSUE TITLE
Blocks injector broken on 1.20.2

### ISSUE THREAD

**Issue by mitchngwen** [ItemsAdder/ItemsAdderBlocksInjector#15]
This plugin does not work on 1.20.2

**Comment by LoneDev6** [comment]
More info on this?
Without any log I can't do anything.
Thanks.

**Comment by mitchngwen** [comment]
[20:40:49] [ServerMain/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[20:40:49] [ServerMain/INFO]: Found new data pack file/iris, loading it automatically
[20:40:51] [ServerMain/INFO]: Loaded 1174 recipes
[20:40:51] [ServerMain/INFO]: Loaded 1271 advancements
[20:40:51] [Server thread/INFO]: Starting minecraft server version 1.20.2
[20:40:51] [Server thread/INFO]: Loading properties
[20:40:51] [Server thread/INFO]: This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
[20:40:52] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:40:52] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:40:52] [Server thread/WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[20:40:52] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 4 worker threads, and gen parallelism of 4 threads
[20:40:53] [Server thread/INFO]: Default game type: SURVIVAL
[20:40:53] [Server thread/INFO]: Generating keypair
[20:40:53] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:40:53] [Server thread/INFO]: Using epoll channel type
[20:40:53] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[20:40:53] [Server thread/INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loading 1 libraries... please wait
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/apache/httpcomponents/httpmime/4.5.14/httpmime-4.5.14.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/mitch/Documents/MC Servers/test/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [ItemsAdder] Loaded library /home/mitch/Documents/MC Servers/test/libraries/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loading 11 libraries... please wait
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4.2/concurrentlinkedhashmap-lru-1.4.2.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/github/ben-manes/caffeine/caffeine/3.0.5/caffeine-3.0.5.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/checkerframework/checker-qual/3.19.0/checker-qual-3.19.0.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/errorprone/error_prone_annotations/2.10.0/error_prone_annotations-2.10.0.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/io/timeandspace/smoothie-map/2.0.2/smoothie-map-2.0.2.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/io/timeandspace/jpsg-core/1.4/jpsg-core-1.4.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/zeroturnaround/zt-zip/1.14/zt-zip-1.14.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/slf4j/slf4j-api/1.6.6/slf4j-api-1.6.6.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/rhino/js/1.7R2/js-1.7R2.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/bsf/bsf/2.4.0/bsf-2.4.0.jar
[20:40:53] [Server thread/INFO]: [SpigotLibraryLoader] [Iris] Loaded library /home/mitch/Documents/MC Servers/test/libraries/commons-logging/commons-logging/1.0.4/commons-logging-1.0.4.jar
[20:40:53] [Server thread/INFO]: [ViaVersion] Loading server plugin ViaVersion v4.9.2
[20:40:53] [Server thread/INFO]: [ViaVersion] ViaVersion 4.9.2 is now loaded. Registering protocol transformers and injecting...
[20:40:54] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[20:40:54] [Server thread/INFO]: [ViaBackwards] Loading translations...
[20:40:54] [Server thread/INFO]: [ViaBackwards] Registering protocols...
[20:40:54] [Via-Mappingloader-0/INFO]: [ViaVersion] Using FastUtil Long2ObjectOpenHashMap for block connections
[20:40:55] [Server thread/INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.2.0-SNAPSHOT-679
[20:40:56] [Server thread/INFO]: [LoneLibs] Loading server plugin LoneLibs v1.0.45
[20:40:56] [Server thread/INFO]: [ItemsAdder] Loading server plugin ItemsAdder v3.6.3-beta-9
[20:40:56] [Server thread/INFO]: [Iris] Loading server plugin Iris v3.0.0-1.19.2-1.20.2
[20:40:56] [Server thread/INFO]: [ViaBackwards] Loading server plugin ViaBackwards v4.9.1
[20:40:56] [Server thread/INFO]: [ItemsAdderBlocksInjector] Loading server plugin ItemsAdderBlocksInjector v0.0.13
[20:40:56] [Server thread/ERROR]: [ItemsAdderBlocksInjector] Error initializing plugin 'itemsadder-blocks-injector_0.0.13.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/type/types/version/ChunkSectionType1_18
	at dev.lone.blocksinjector.custom_blocks.nms.packetlistener.v1_20_R2.<init>(v1_20_R2.java:34) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.v1_20_R2.registerListener(v1_20_R2.java:56) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at dev.lone.blocksinjector.Main.onLoad(Main.java:24) ~[itemsadder-blocks-injector_0.0.13.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.2.jar:git-Paper-318]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-318]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:514) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-318]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.api.type.types.version.ChunkSectionType1_18
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 12 more
[20:40:56] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:40:56] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.2.0-SNAPSHOT-679
[20:40:56] [Server thread/INFO]: [LoneLibs] Enabling LoneLibs v1.0.45
[20:40:56] [Server thread/INFO]: [Iris] Enabling Iris v3.0.0-1.19.2-1.20.2
[20:40:57] [Server thread/INFO]: [Iris] [STDOUT] §l§8[§l§aIris§l§8]§r§7: §fLocating NMS Binding for v1_20_R2
[20:40:57] [Server thread/WARN]: Nag author(s): '[cyberpwn, NextdoorPsycho, Vatuu]' of 'Iris v3.0.0-1.19.2-1.20.2' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[20:40:57] [Server thread/INFO]: [Iris] [STDOUT] §l§8[§l§aIris§l§8]§r§7: §fCraftbukkit v1_20_R2  NMSBinding Successfully Bound
[20:40:57] [Server thread/INFO]: [Iris] [STDOUT] §l§8[§l§aIris§l§8]§r§7: §fEnabled Iris SafeGuard
[20:40:57] [Server thread/INFO]: [Iris] [STDOUT] §l§8[§l§aIris§l§8]§r§7: §fChecking for possible conflicts..
[20:40:58] [Server thread/INFO]: [Iris]: Loading ExternalDataProvider...
[20:40:58] [Server thread/INFO]: [Iris]: Version Information: git-Paper-318 (MC: 1.20.2) | 1.20.2-R0.1-SNAPSHOT
[20:40:58] [Server thread/INFO]: [Iris]: We recommend using Purpur for the best experience with Iris.
[20:40:58] [Server thread/INFO]: [Iris]: Purpur is a fork of Paper that is optimized for performance and stability.
[20:40:58] [Server thread/INFO]: [Iris]: Plugins that work on Spigot / Paper work on Purpur.
[20:40:58] [Server thread/INFO]: [Iris]: You can download it here: https://purpurmc.org
[20:40:58] [Server thread/INFO]: [ItemsAdderBlocksInjector] Enabling ItemsAdderBlocksInjector v0.0.13
[20:40:58] [Server thread/INFO]: Preparing level "world"
[20:40:58] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:40:59] [Server thread/INFO]: Time elapsed: 425 ms
[20:40:59] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[20:40:59] [Server thread/INFO]: Time elapsed: 113 ms
[20:40:59] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[20:40:59] [Server thread/INFO]: Time elapsed: 77 ms
[20:40:59] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v4.9.2
[20:40:59] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.20.2 (764)
[20:40:59] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v3.6.3-beta-9
[20:41:00] [Server thread/INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_20_R2! Trying to find NMS support
[20:41:00] [Server thread/INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_20_R2' loaded!
[20:41:02] [Server thread/INFO]: [ItemsAdder] 
  ___  ___        __        __   __   ___  __      ItemsAdder 3.6.3-beta-9
|  |  |__   |\/| /__`  /\  |  \ |  \ |__  |__)     LoneLibs 1.0.45
|  |  |___  |  | .__/ /--\ |__/ |__/ |___ |  \     Paper git-Paper-318 (MC: 1.20.2)
                                               
[20:41:03] [Server thread/WARN]: [ProtocolLib] [PacketFilterManager] Plugin ItemsAdder tried to register listener for unknown packet ADD_RESOURCE_PACK[PLAY, SERVER, 68, classNames: [net.minecraft.network.protocol.game.PacketPlayOutResourcePackPushPacket, net.minecraft.network.protocol.game.ClientboundResourcePackPushPacketPacket] (unregistered)] [direction: from SERVER]
[20:41:04] [Server thread/INFO]: [Iris]: Enabled ExternalDataProvider for ItemsAdder.
[20:41:04] [Server thread/INFO]: [ViaBackwards] Enabling ViaBackwards v4.9.1
[20:41:04] [Server thread/INFO]: Running delayed init tasks
[20:41:04] [Craft Scheduler Thread - 4 - ViaVersion/INFO]: [ViaVersion] Finished mapping loading, shutting down loader executor!
[20:41:04] [Server thread/INFO]: [Iris]: Server type & version: git-Paper-318 (MC: 1.20.2)
[20:41:04] [Server thread/INFO]: [Iris]: Server OS: Linux (amd64)
[20:41:04] [Server thread/INFO]: [Iris]: Server Cpu: Intel(R) Xeon(R) CPU           X5672  @ 3.20GHz
[20:41:04] [Craft Scheduler Thread - 2 - ItemsAdder/INFO]: [ItemsAdder] [License] Spigot product licensed to: mitchngwen (695187)
[20:41:04] [Server thread/INFO]: [Iris]: Process Threads: 16
[20:41:04] [Server thread/INFO]: [Iris]: Process Memory: 8192 MB
[20:41:04] [Server thread/INFO]: [Iris]: Bukkit version: 1.20.2-R0.1-SNAPSHOT
[20:41:04] [Server thread/INFO]: [Iris]: Java version: 17
[20:41:04] [Server thread/INFO]: [Iris]: Custom Biomes: 96
[20:41:04] [Server thread/INFO]: [Iris]: Version Information: git-Paper-318 (MC: 1.20.2) | 1.20.2-R0.1-SNAPSHOT
[20:41:04] [Server thread/INFO]: [Iris]: We recommend using Purpur for the best experience with Iris.
[20:41:04] [Server thread/INFO]: [Iris]: Purpur is a fork of Paper that is optimized for performance and stability.
[20:41:04] [Server thread/INFO]: [Iris]: Plugins that work on Spigot / Paper work on Purpur.
[20:41:04] [Server thread/INFO]: [Iris]: You can download it here: https://purpurmc.org
[20:41:04] [Server thread/INFO]: [Iris]: Custom Dimensions: 1
[20:41:04] [Server thread/INFO]: [Iris]:   overworld v3900
[20:41:04] [Server thread/INFO]: [Iris]: 

            @@@@@@@@@@@@@@@@@
         @@&&&&&&&&&&&&&&&   .(((()))).                     
        @@@&&&&&&&&&&&&&  .((((((())))))).                  
        @@@&&&&&&&&&&&&  ((((((((()))))))))                @
        @@@&&&&@@@@@&    ((((((((-)))))))))               @@
        @@@&&            ((((((({ }))))))))            &&@@@     Iris
        @@               ((((((((-)))))))))    &@@@@@&&&&@@@     by Volmit Software
        @                ((((((((()))))))))  &&&&&&&&&&&&@@@     v3.0.0-1.19.2-1.20.2
                          '((((((()))))))'  &&&&&&&&&&&&&@@@
                             '(((())))'   &&&&&&&&&&&&&&&@@
                                       @@@@@@@@@@@@@@@@@

[20:41:04] [Server thread/INFO]: [Iris]: Iris is running Stable
[20:41:04] [Server thread/INFO]: [Iris]: 0 Conflicts found
[20:41:04] [Server thread/INFO]: [ItemsAdder] [Pack] Extracting internal contents from .jar
[20:41:04] [Server thread/INFO]: [ItemsAdder] [Pack] DONE extracting internal contents from .jar
[20:41:05] [Server thread/INFO]: Done (13.949s)! For help, type "help"
[20:41:05] [Server thread/INFO]: Timings Reset
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Loaded 7 items
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/188 REAL block IDs
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/750 REAL_NOTE block IDs
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/127 REAL_WIRE block IDs
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 0/14 FIRE block IDs
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] Used 27/6608 font_images
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded 1 categories
[20:41:06] [Craft Scheduler Thread - 1 - ItemsAdder/INFO]: [ItemsAdder] [Init] Loaded successfully.
[20:41:08] [Craft Scheduler Thread - 2 - Iris/INFO]: [Iris]: Updating paper.yml watchdog early-warning-delay: 10000 -> 900000 (3 minutes)
[20:41:08] [Craft Scheduler Thread - 2 - Iris/INFO]: [Iris]: You can disable this change (autoconfigureServer) in Iris settings, then change back the value.
[20:41:08] [Craft Scheduler Thread - 2 - Iris/INFO]: [Iris]: Checking Data Packs...
[20:41:10] [Craft Scheduler Thread - 2 - Iris/INFO]: [Iris]: Data Packs Setup!
[20:41:21] [Server thread/INFO]: Server Plugins (7):
[20:41:21] [Server thread/INFO]: Bukkit Plugins:
[20:41:21] [Server thread/INFO]:  - Iris, ItemsAdder, ItemsAdderBlocksInjector, LoneLibs, ProtocolLib, ViaBackwards, ViaVersion

**Comment by mitchngwen** [comment]
https://pastebin.com/N3Gg4fN9

**Comment by LoneDev6** [comment]
It's due to ViaVersion.
I will release a fix, thanks.
