### ISSUE TITLE
Broken on 1.20.6

### ISSUE THREAD

**Issue by charlieslost** [ItemsAdder/ItemsAdderBlocksInjector#16]
https://mclo.gs/bxRuUbQ

**Comment by charlieslost** [comment]
`[13:01:34] [Server thread/INFO]: [ItemsAdderBlocksInjector] Loading server plugin ItemsAdderBlocksInjector v0.0.14
[13:01:34] [Server thread/ERROR]: [ItemsAdderBlocksInjector] Error initializing plugin 'itemsadder-blocks-injector_0.0.14.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at itemsadder-blocks-injector_0.0.14.jar/dev.lone.blocksinjector.custom_blocks.nms.Nms.findImplementation(Nms.java:42) ~[itemsadder-blocks-injector_0.0.14.jar:?]
	at itemsadder-blocks-injector_0.0.14.jar/dev.lone.blocksinjector.custom_blocks.nms.blocksmanager.CustomBlocksInjector.initNms(CustomBlocksInjector.java:42) ~[itemsadder-blocks-injector_0.0.14.jar:?]
	at itemsadder-blocks-injector_0.0.14.jar/dev.lone.blocksinjector.Main.onLoad(Main.java:23) ~[itemsadder-blocks-injector_0.0.14.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1150) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2233-0d6766e]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

Heres the error incase the link expires, the plugin still loads.

**Comment by LoneDev6** [comment]
Because it's not implemented, will be in the future.
Anyway code is public, anyone can add compatibility
