### ISSUE TITLE
ViaVersion required as a dependency

### ISSUE THREAD

**Issue by RareMaker50** [ItemsAdder/ItemsAdderBlocksInjector#2]
[10:53:15 ERROR]: Could not load 'plugins/itemsadder-blocks-injector_0.0.4.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ViaVersion]. Please download and install these plugins to run 'ItemsAdderBlocksInjector'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
That error comes up whenever you try load the plugin with just Iris worldgen and IA, because on the spigot page it says you only need IA to load the plugin

**Comment by RareMaker50** [comment]
This can be fixed by opening up the jar using a zip manager (winrar, 7zip etc.), going into plugin.yml and removing ViaVersion from the dependency list 
![image](https://user-images.githubusercontent.com/58754060/169692236-4c936d27-7e84-456a-9562-ddd56e52477a.png)

**Comment by thefourcraft** [comment]
# About the bug 🐛 
The [ItemsAdderBlocksInjector](https://github.com/ItemsAdder/ItemsAdderBlocksInjector) keeps the dependency for ViaVersion.
This is not critical it is just an error in the console 🔴 
**This is the complete log of the server:**
1. https://bin.bloom.host/eviqeqaxes
2. https://mclo.gs/fqx4PjJ
## Things @RareMaker50 tried to do
### Removing iris
* remove the plugin
* start the server 
* put it back in
* start the server
### Removing ItemsAdderBlocksInjector
* removing ItemsAdderBlocksInjector
* starting the server
* putting ItemsAdderBlocksInjector back in the server
* starting the server 
### removing the dependency manually
* Opnning the .jar file for ItemsAdderBlocksInjector
* going to the plugin.yml
* removing the dependency from the "code".
Removing the dependency manually won't help 😞 
this is the error after manually removing the dependency:
![image](https://user-images.githubusercontent.com/90725541/169692667-f61cd3e2-2a37-4cc0-8d79-8219c92b5816.png)
## How To Fix It Now?
It would be best if you kept using ViaVersion until the bug is fixed...

**Comment by LoneDev6** [comment]
This is not a bug, viaversion is currently needed.
The source is public so anyone can contribute. I don't have a solution that works without Viaversion.

**Comment by RareMaker50** [comment]
Oh alright, Is it possible for you to change the spigot page and adding ViaVersion into the plugins you require so it won't cause any confusion with anyone in the future?
